### ISSUE TITLE
Can you give me the demo to connect elasticsearch?

### ISSUE THREAD

**Issue by sunyizhen** [albertocsm/presto#30]
such as the file of hive.properties
and more the elasticsearch plugin needs some jars ?
Thank you !

**Comment by FlavioF** [comment]
Hi

You must configure two files:

/myPath/myschemafile.json
```
{
    "mySchema": [
        {
            "name": "TableName1",
            "sources": [
                {
                    "hostAddress": "__ES_HOST__",
                    "port": __ES_PORT__,
                    "clusterName": "__ES_CLUSTER_NAME__",
                    "type": "__ES_TYPE__",
		    "index": "__ES_INDEX_PATTERN__"
                }
            ]
        },
        {
            "name": "TableName2",
            "sources": [
               {
                    "hostAddress": "__ES_HOST__",
                    "port": __ES_PORT__,
                    "clusterName": "__ES_CLUSTER_NAME__",
                    "type": "__ES_TYPE_2__",
		    "index": "__ES_INDEX_PATTERN_2__"
                }
            ]
        },
        {
             .........
        }
    ]
}
```

.../presto/etc/catalog/es.properties
```
connector.name=elasticsearch
elasticsearch.metadata-uri=file:///myPath/myschemafile.json
```

Is this enough for you?

**Comment by sunyizhen** [comment]
Yes, this is enough for me ,but i want to connect elasticsearch 2.3 ,can you give me some suggesttions?

At 2016-12-14 01:28:41, "Flávio Ferreira" <notifications@github.com> wrote:


Hi

You must configure two files.

Firstly a file like this one:
/myPath/myschemafile.json

{
    "mySchema": [
        {
            "name": "TableName1",
            "sources": [
                {
                    "hostAddress": "__ES_HOST__",
                    "port": __ES_PORT__,
                    "clusterName": "__ES_ROUTES_CLUSTER_NAME__",
                    "type": "__ES_TYPE__",
		    "index": "__ES_INDEX_PATTERN__"
                }
            ]
        },
        {
            "name": "TableName2",
            "sources": [
               {
                    "hostAddress": "__ES_HOST__",
                    "port": __ES_PORT__,
                    "clusterName": "__ES_ROUTES_CLUSTER_NAME__",
                    "type": "__ES_TYPE_2__",
		    "index": "__ES_INDEX_PATTERN_2__"
                }
            ]
        },
        {
             .........
        }
    ]
}


Secondly another file:
.../presto/etc/catalog/es.properties

connector.name=elasticsearch
elasticsearch.metadata-uri=file:///myPath/myschemafile.json


Is this enough for you?

**Comment by sunyizhen** [comment]
Yes, this is enough for me ,but i want to connect elasticsearch 2.3 ,can you give me some suggesttions?

**Comment by albertocsm** [comment]
the connector is tested and known to be working with ES 1.6
2.x or 4.x was not tested, but i suspect there'r a few breaking changes to address. I would start by forking and updating ES mvn reference and start fixing whatever it breaks
