### ISSUE TITLE
implicit all-table-indices performance

### ISSUE THREAD

**Issue by albertocsm** [albertocsm/presto#5]
when no index is specified for a type/table, all indices, its mappings and columns are taken in consideration. this is not performant at all;

if a specific index is to be queried to determine the table columns, u need to specify the index name on the table mapping
e.g.

```
{
            "name": "fancyPantsTable",
            "sources": [
                {
                    "hostaddress": "127.0.0.1",
                    "port": 9300,
                    "clusterName": "some-cluster-name",
                    "type": "document-type-name",
                     "index": "one-index-for-this-table"
                }
            ]
}
```

if the table is to be mapped to more then one index but it still is a finite and pre determined number of indices, one can specify them with multiple entries in the previous array

**Comment by FlavioF** [comment]
Now it allow to add multiple index or a group of index like an ES query.
Example:

<pre>
{
            "name": "fancyPantsTable",
            "sources": [
                {
                    "hostaddress": "127.0.0.1",
                    "port": 9300,
                    "clusterName": "some-cluster-name",
                    "type": "document-type-name",
                     "index": "one-index-for-this-table, two-index-for-this-table, *-index-for-this-table"
                }
            ]
}
</pre>
